$image = /home/sun/Pictures/Wallpapers/building.jpg

$background = rgba(111414ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2e3131ff)

$inverse_primary = rgba(346666ff)

$inverse_surface = rgba(e2e3e2ff)

$on_background = rgba(e2e3e2ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(003736ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(002020ff)

$on_primary_fixed_variant = rgba(194e4eff)

$on_secondary = rgba(223433ff)

$on_secondary_container = rgba(d4e8e7ff)

$on_secondary_fixed = rgba(0c1e1eff)

$on_secondary_fixed_variant = rgba(384a4aff)

$on_surface = rgba(e2e3e2ff)

$on_surface_variant = rgba(bfc8c7ff)

$on_tertiary = rgba(4c2613ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(321203ff)

$on_tertiary_fixed_variant = rgba(673c27ff)

$outline = rgba(8a9292ff)

$outline_variant = rgba(404848ff)

$primary = rgba(9cd0cfff)

$primary_container = rgba(679998ff)

$primary_fixed = rgba(b8ecebff)

$primary_fixed_dim = rgba(9cd0cfff)

$scrim = rgba(000000ff)

$secondary = rgba(b6cac9ff)

$secondary_container = rgba(3a4c4cff)

$secondary_fixed = rgba(d2e7e5ff)

$secondary_fixed_dim = rgba(b6cac9ff)

$shadow = rgba(000000ff)

$source_color = rgba(548685ff)

$surface = rgba(111414ff)

$surface_bright = rgba(373a39ff)

$surface_container = rgba(1d2020ff)

$surface_container_high = rgba(282a2aff)

$surface_container_highest = rgba(333535ff)

$surface_container_low = rgba(191c1cff)

$surface_container_lowest = rgba(0c0f0fff)

$surface_dim = rgba(111414ff)

$surface_tint = rgba(9cd0cfff)

$surface_variant = rgba(404848ff)

$tertiary = rgba(f6b99dff)

$tertiary_container = rgba(bb846bff)

$tertiary_fixed = rgba(ffdbccff)

$tertiary_fixed_dim = rgba(f6b99dff)

