#█▀▀ █░░ █░█ █▀▄ ▀█▀ █▄░█ ▄▀█
#█░░ █▄▄ █▄█ █▄█ ░█░ █░▀█ █▀▄
# courtesy of glourius gemini pro 2.5 the above is "Plugins"

plugin {
    hyprexpo {
        columns = 3
        gap_size = 5
        bg_col = rgb(000000)
        workspace_method = first 1   # [center/first] [workspace] e.g. first 1 or center m+1
        skip_empty = true

        #enable_gesture = true        # laptop touchpad
        #gesture_fingers = 3          # 3 or 4
        #gesture_distance = 350       # how far is the "max"
        #gesture_positive = true      # positive = swipe down. Negative = swipe up.
    }
}

#multi monitor workspace setup
plugin {
    split-monitor-workspaces {
        count = 10
        enable_notifications = 0
        enable_persistent_workspaces = 0
    }
}