# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█


# General Floating Rules
windowrule = match:title ^(Calculator)$, float 1, center 1, workspace 4
windowrule = match:class ^(feh)$, float 1, center 1
windowrule = match:class ^(localsend)$, float 1, center 1
windowrule = match:title ^(Characters)$, float 1, center 1
windowrule = match:class ^(waypaper)$, float 1, center 1

## Dialog rules
windowrule {
    name = dialog_windows
    match:title = ^(Open File|Select a File|Choose wallpaper|Open Folder|Save As|Library|File Upload).*$
    float = 1
    center = 1
}

# Game specific rules
windowrule {
    name = 0_heroes_of_the_storm
    match:title = ^(Heroes.*)$
    float = 1
    center = 1
    workspace = 2 silent
    monitor = DP-1
    size = 3314, 1387
    move = 727, 50
}
windowrule {
    name = terraria
    match:initial_title = ^(Terraria*)(.*)$
    float = 1
    center = 1
    workspace = 2 silent
    monitor = DP-1
    size = 3840 1386
}

windowrule {
    name = minecraft
    match:class = ^(Minecraft).*
    float = false
    center = true
    workspace = 3 silent
    monitor = DP-1
}

windowrule {
    name = Slay_the_spire_2
    match:class = ^(Slay the Spire 2)$
    workspace = 2 silent
    float = 1
    monitor = DP-1
    immediate = 1
    move = 967, 52
	size = 3122, 1385

}
windowrule {
    name = cyberpunk
    match:title = ^(REDlauncher)$
    center = 1
}

windowrule {
    name = warframe
    match:title = ^(Warframe)$
    center = 1
}


windowrule {
    #captures any game launched through steam, applies fullscreen and places on workspace 2
    #KEEP THIS BELOW ALL SPECIFIC GAME WINDOWRULES
    name = generic_game
    match:class = ^(steam_app)(.*)$
    workspace = 2 silent
    float = 0
    monitor = DP-1
    immediate = 1

}

windowrule {
    name = steam
    match:class = ^(steam)$
    float = false
    workspace = 5 silent
    monitor = DP-1
}

windowrule {
    name = vekstop
    match:class = ^(vesktop).*$
    float = false
    workspace = 11 silent
    monitor = DP-2
}

windowrule {
    name = spotify
    match:class = ^(spotify).*$
    float = false
    workspace = 12 silent
    monitor = DP-2
}

windowrule {
    name = steam friends list
    match:title = Friends List
    float = true
    center = true
}

#windowrule {
#    name = steam message
#    match:title = ^((?!steam).*)$
#    match:class = ^(steam)$
#    float = true
#    center = true
#}



#Steam Tearing
#windowrule {
#    name = steam_tearing
#    match:class = ^(steam_app).*$
#    immediate = 1
#    float = true
#}

windowrule {
    name = Generic Tearing
    match:title = .*\.exe
    immediate = 1
}



# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
#windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█


