


#listener {
#    #timeout = 300                            # 5 minutes in seconds
#    on-timeout = hyprctl dispatch dpms off   # Command to run when inactive
#    on-resume = hyprctl dispatch dpms on     # Command to run when activity resumes
#}

#listener {
#    timeout = 10                            # in seconds.
#    on-timeout = notify-send "You are idle!" # command to run when timeout has passed.
#    on-resume = notify-send "Welcome back!"  # command to run when activity is detected after timeout has fired.
#}

general {
    lock_cmd = pidof hyprlock || hyprlock       # This catches `loginctl lock-session`
    before_sleep_cmd = loginctl lock-session    # Ensures it locks before system suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # Wakes up the screen after suspend
}
