# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# █▀ █▀█ █░█ █▀█ █▀▀ █▀▀
# ▄█ █▄█ █▄█ █▀▄ █▄▄ ██▄

source = ~/.config/hypr/source/keybinds.conf
source = ~/.config/hypr/source/rules.conf # windows (ew) and layering rules
source = ~/.config/hypr/source/colors.conf #matugen colors
source = ~/.config/hypr/source/appearance.conf # shared theme settings
source = ~/.config/hypr/source/plugins.conf # plugins idk what else would go here bozo
source = ~/.config/hypr/source/monitors.conf # screeeeeeeeeeeeeeens
source = ~/.config/hypr/source/autostart.conf #autoooooooooo


