listener {
    #timeout = 300                            # 5 minutes in seconds
    timeout = 20                             # 20 second timeout
    on-timeout = hyprctl dispatch dpms off   # Command to run when inactive
    on-resume = hyprctl dispatch dpms on     # Command to run when activity resumes
}

#listener {
#    timeout = 10                            # in seconds.
#    on-timeout = notify-send "You are idle!" # command to run when timeout has passed.
#    on-resume = notify-send "Welcome back!"  # command to run when activity is detected after timeout has fired.
#}